sonar.projectKey=cortexium-labs_vectra
sonar.organization=cortexium-labs
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
sonar.exclusions=**/obj/**,**/bin/**,**/*.Designer.cs
sonar.coverage.exclusions=**/Program.cs,**/Configuration/**
